name: tests

on:
  pull_request
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd apps && npm run install-all && npm run build-all && npm run test-all
    
