name: tests

on:
  pull_request:
    paths:
      - apps/tickets/**
      - apps/common/**
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd apps/common && npm install && npm run build
      - run: cd apps/tickets && npm install && npm run test
    
